### ISSUE TITLE
GUI at localhost:1234 throws a build error

### ISSUE THREAD

**Issue by ghost** [DRIVER-EU/chemical_hazard_tool#5]
### Description

After following the [installation steps](https://github.com/DRIVER-EU/chemical_hazard_tool#installation) the GUI on http://localhost:1234/ throws a build error when visited in the browser.

### Steps to reproduce

1. Clone the repository
2. Follow the [installation steps](https://github.com/DRIVER-EU/chemical_hazard_tool#installation) (`docker-compose up`, etc...)
3. Go to http://localhost:1234/

#### Expected outcome

Some sort of GUI.

#### Actual outcome

An HTML page with the title "🚨 Build Error" and the following contents:

```log
C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\mithril-ui-form\lib\index.esm.js: Unknown version 59 of op_mob

    at Function.select (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\browserslist@4.12.0\node_modules\browserslist\index.js:1086:17)
    at C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\browserslist@4.12.0\node_modules\browserslist\index.js:336:33
    at Array.reduce ()
    at resolve (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\browserslist@4.12.0\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\browserslist@4.12.0\node_modules\browserslist\index.js:443:21)
    at getTargets (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\@babel\helper-compilation-targets@7.10.1_@babel+core@7.10.1\node_modules\@babel\helper-compilation-targets\lib\index.js:195:48)
    at C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\@babel\preset-env@7.10.1_@babel+core@7.10.1\node_modules\@babel\preset-env\lib\index.js:247:57
    at Object.default (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\@babel\helper-plugin-utils@7.10.1\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12)
    at getEnvPlugins (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\parcel-bundler@1.12.4\node_modules\parcel-bundler\src\transforms\babel\env.js:62:34)
    at getEnvConfig (C:\Users\username\repos\assistance\chemical_hazard_tool\packages\gui\node_modules\.pnpm\parcel-bundler@1.12.4\node_modules\parcel-bundler\src\transforms\babel\env.js:21:28)
```

This seems to be related to [this issue](https://github.com/browserslist/browserslist/issues/537) of the browserslist package. Using browserslist >= 4.14.4 should solve this issue. However, I'm unsure how to direct all packages using browserslist to use that version.

**Comment by ghost** [comment]
For now "resolved" this by deleting the `package-lock.json` files from `\packages\gui\` and then running `pnpm m i`. However, this is just a solution for me and is not sustainable.

**Comment by ghost** [comment]
Resolution above is sufficient
